INSERT INTO pattern_card (pattern, difficulty) VALUES ('040y6r020000rp1by000', 3);
INSERT INTO pattern_card (pattern, difficulty) VALUES ('0br000450bb20r56r310', 5);
INSERT INTO game (die, state) VALUES ('R4Y2B3B6', 'NEW');
INSERT INTO game (die, state) VALUES ('G2P5R2P3', 'ONGOING');
INSERT INTO player (name) VALUES ('Maurits');
INSERT INTO player (name) VALUES ('Frank');
INSERT INTO objective_card (name, description, type, config) VALUES ('Blue tints', 'Sum of values on blue die', 'Private', 'B');
INSERT INTO objective_card (name, description, type, config) VALUES ('Yellow tints', 'Sum of values on yellow die', 'Private', 'Y');
INSERT INTO game_player (game_id, player_id, player_score, board_pattern, objective_card_id) VALUES (1, 1, 250, '', 1);
INSERT INTO game_player (game_id, player_id, player_score, board_pattern, objective_card_id) VALUES (1, 2, 100, '', 1);
